### ISSUE TITLE
Error in setwd(wd) : cannot change working directory

### ISSUE THREAD

**Issue by wudiweishao** [stanfill/apsimr#1] opened 2020-06-29 05:27 UTC
Hi, I have installed the APSIM 710 in my computer and when I run the examples of package apsimr in RStudio, an error accured(as the title). the information and code in follows: 
![VYG)X C})D6L53}JHCA~C%P](https://user-images.githubusercontent.com/22288341/85975464-b3f77600-ba0a-11ea-8ade-4d9e1ebdd007.png)

library(apsimr)

## Not run: 
apsimExe <-"C:/Program Files (x86)/Apsim710-r4203/Model/Apsim.exe"
apsimWd <- "~/APSIM"
toRun <- c("Centro.apsim", "Continuous Wheat.apsim")
results <- apsim(exe = apsimExe, wd = apsimWd, files = toRun)
Error in setwd(wd) : cannot change working directory
###
but if I change the work directory,  and ignore the parameter of "wd",everything is fine
apsimExe <-"C:/Program Files (x86)/Apsim710-r4203/Model/Apsim.exe"
toRun <- c("Centro.apsim", "Continuous Wheat.apsim")
apsimWd<-setwd("C:/Program Files (x86)/APSIM710-r4203/Examples")
results <- apsim(exe = apsimExe,  files =toRun)
#output 
> results
$`Centro`
        Date year day DaysAfterSowing biomass green_biomass stover_wt  yield lai esw_layr.. root_depth
2 1989-03-20 1989  79             179  9212.5        5675.2    829.84  914.1   0     43.787   1499.976
3 1990-03-18 1990  77             177 11626.4        7463.2   1046.64 1160.0   0     11.990   1499.991

$`Continuous Wheat`
        Date biomass  yield grain_protein grain_size     esw
2 1942-10-11  9545.8 3583.2        16.417      0.041 326.700
3 1943-10-29 13445.1 5040.1        16.448      0.033 266.912
4 1945-10-22 12805.3 4887.7        16.078      0.041 286.493
5 1947-10-24 14758.1 5800.6        13.786      0.041 323.269
6 1948-10-29 13575.9 4329.3        10.896      0.029 294.760
7 1949-10-26 13677.3 4662.1        11.348      0.032 393.612
8 1950-10-12  5477.1 2037.9        16.443      0.041 537.431
### but if I try other examples in the vegennate of apsimr
the error accured again:
meanYield<-function(x){
  return(mean(x$lai_cowpea))
}
n <- 75
parValues <- data.frame(SoilCN = runif(n, 5, 25),
                        DiffusConst = runif(n, 20, 50), CNCov = runif(n, 0, 1))
apsimExe <-"C:/Program Files (x86)/Apsim75-r3008/Model/Apsim.exe"
apsimWd <- "~/APSIM"
apsimVars <- c("SoilOrganicMatter/SoilCN", "SoilWater/DiffusConst", "SoilWater/CNCov")
apsimWd<-setwd("C:/Program Files (x86)/APSIM710-r4203/Examples")
apsimFile <- "Canopy.apsim"

emulRes <- apsim_emul_sa(model = apsim_vector, X = parValues, method = "singleGAM",
                         exe = apsimExe, wd=apsimWd, vars = apsimVars, to.run = apsimFile,
                         g = meanYield, overwrite = TRUE)
Error in apsim(exe = exe, wd = wd, files = to.run) : 
  An error occured when trying to run APSIM.  Please check your arguments again, especially the path to APSIM.exe.

any idear about this? thanks!

**Comment by femiguez** [comment] 2020-07-02 22:51
My understanding is that this package is not under development. Package apsimx provides similar functionality. https://CRAN.R-project.org/package=apsimx

**Comment by stanfill** [comment] 2020-07-06 16:35
Fernando is right, and I encourage you to use apsimx if possible.  In fact, 'apsimr' was just removed from CRAN because of some weird error that I didn't fix in time.

That being said, I think the problem is the 'apsimWD' variable.  Replace
`apsimWd<-setwd("C:/Program Files (x86)/APSIM710-r4203/Examples")` 
with 
`apsimWd<-"C:/Program Files (x86)/APSIM710-r4203/Examples"`

I'm pretty sure that's the fix so I'm closing.  Feel free to reopen if I'm wrong.

**Closed as completed by stanfill** 2020-07-06 16:35 UTC
